using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NLog;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;

namespace WorldServer.logic
{
    /// <summary>
    /// Loads community dungeon behaviors from .cs files at server startup.
    /// Each .cs file contains user-submitted behavior code wrapped in a template.
    /// Files are validated with BehaviorCodeAnalyzer before compilation.
    /// </summary>
    internal static class CSharpBehaviorLoader
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();

        // Cached MetadataReferences — created once, reused for all compilations
        private static List<MetadataReference> _cachedReferences;
        private static readonly object _refLock = new object();

        private const string TEMPLATE = @"
using WorldServer.logic;
using WorldServer.logic.behaviors;
using WorldServer.logic.transitions;
using WorldServer.logic.loot;
using Shared.resources;

namespace WorldServer.logic.db.community
{{
    public static class Behavior_{0}
    {{
        public static void Register(BehaviorDb db)
        {{
            {1}
        }}
    }}
}}
";

        private static List<MetadataReference> GetCachedReferences()
        {
            if (_cachedReferences != null)
                return _cachedReferences;

            lock (_refLock)
            {
                if (_cachedReferences != null)
                    return _cachedReferences;

                var refs = new List<MetadataReference>
                {
                    MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(State).Assembly.Location),
                };

                var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location);
                var systemRuntime = Path.Combine(runtimeDir, "System.Runtime.dll");
                if (File.Exists(systemRuntime))
                    refs.Add(MetadataReference.CreateFromFile(systemRuntime));

                var systemCollections = Path.Combine(runtimeDir, "System.Collections.dll");
                if (File.Exists(systemCollections))
                    refs.Add(MetadataReference.CreateFromFile(systemCollections));

                var sharedAssembly = AppDomain.CurrentDomain.GetAssemblies()
                    .FirstOrDefault(a => a.GetName().Name == "Shared");
                if (sharedAssembly != null)
                    refs.Add(MetadataReference.CreateFromFile(sharedAssembly.Location));
                else
                    Log.Warn("[CSharpBehaviorLoader] Shared assembly not loaded — ConditionEffectIndex will not resolve");

                _cachedReferences = refs;
                return _cachedReferences;
            }
        }

        public static void LoadAll(BehaviorDb db, string resourcePath)
        {
            var dir = Path.Combine(resourcePath, "behaviors", "community");
            Log.Info($"[CSharpBehavior] Looking for .cs files in: {dir}");
            if (!Directory.Exists(dir))
            {
                Log.Warn($"[CSharpBehavior] Directory does not exist: {dir}");
                return;
            }

            var files = Directory.GetFiles(dir, "*.cs");
            Log.Info($"[CSharpBehavior] Found {files.Length} .cs files: {string.Join(", ", files.Select(Path.GetFileName))}");
            if (files.Length == 0)
                return;

            var total = 0;

            foreach (var file in files)
            {
                try
                {
                    if (LoadFile(db, file))
                        total++;
                }
                catch (Exception e)
                {
                    Log.Error($"[CSharpBehavior] Failed to load {Path.GetFileName(file)}: {e.Message}");
                }
            }

            if (total > 0)
                Log.Info($"[CSharpBehavior] Loaded {total} community C# behavior files.");
        }

        private static bool LoadFile(BehaviorDb db, string filePath)
        {
            var fileName = Path.GetFileNameWithoutExtension(filePath);
            var sourceCode = File.ReadAllText(filePath);

            // Check if this is raw user code (no namespace declaration) or a full file
            bool isWrapped = sourceCode.Contains("namespace ");
            string fullSource;

            if (isWrapped)
            {
                // Already a complete file (generated by AdminDashboard approval)
                fullSource = sourceCode;
            }
            else
            {
                // Raw user code — wrap in template
                var safeName = SanitizeClassName(fileName);
                fullSource = string.Format(TEMPLATE, safeName, sourceCode);
            }

            // Validate with whitelist analyzer — returns the parsed SyntaxTree for reuse
            var (isValid, errors, syntaxTree) = BehaviorCodeAnalyzer.Analyze(fullSource);
            if (!isValid || syntaxTree == null)
            {
                Log.Error($"[CSharpBehavior] '{fileName}' failed validation:");
                foreach (var err in errors)
                    Log.Error($"  {err}");
                return false;
            }

            // Compile with Roslyn using cached references and reused syntax tree
            var references = GetCachedReferences();

            var compilation = CSharpCompilation.Create(
                $"CommunityBehavior_{fileName}",
                syntaxTrees: new[] { syntaxTree },
                references: references,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            );

            // Emit to memory
            using var ms = new MemoryStream();
            var emitResult = compilation.Emit(ms);

            if (!emitResult.Success)
            {
                var failures = emitResult.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error);
                Log.Error($"[CSharpBehavior] Compilation failed for '{fileName}':");
                foreach (var diag in failures)
                    Log.Error($"  {diag.GetMessage()}");
                return false;
            }

            // Load the compiled assembly
            ms.Seek(0, SeekOrigin.Begin);
            var assembly = AssemblyLoadContext.Default.LoadFromStream(ms);

            // Find and invoke the Register method
            var registerType = assembly.GetTypes()
                .FirstOrDefault(t => t.GetMethod("Register", BindingFlags.Public | BindingFlags.Static) != null);

            if (registerType == null)
            {
                Log.Error($"[CSharpBehavior] No Register(BehaviorDb) method found in '{fileName}'");
                return false;
            }

            var registerMethod = registerType.GetMethod("Register", BindingFlags.Public | BindingFlags.Static);
            try
            {
                registerMethod.Invoke(null, new object[] { db });
            }
            catch (TargetInvocationException ex)
            {
                Log.Error($"[CSharpBehavior] Register() threw exception in '{fileName}': {ex.InnerException?.Message ?? ex.Message}");
                return false;
            }
            catch (Exception ex)
            {
                Log.Error($"[CSharpBehavior] Failed to invoke Register() in '{fileName}': {ex.Message}");
                return false;
            }

            Log.Info($"[CSharpBehavior] Successfully loaded '{fileName}'");
            return true;
        }

        private static string SanitizeClassName(string name)
        {
            // Convert to valid C# identifier
            var chars = name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray();
            var result = new string(chars);
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = "_" + result;
            return result;
        }
    }
}
