#8812938
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish AdminDashboard -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
RUN mkdir -p /data
COPY --from=build /app/AdminDashboard/admin.json /data/admin.json
CMD ["dotnet", "AdminDashboard.dll"]
